export const PRESETS_REGISTRY = {
  base: [
    {
      id: 'standard-particle',
      label: 'Standard Particle',
      engine: 'particles',
      description: 'A neutral particle emitter used as the basic render smoke test.',
      config: {
        name: 'Standard Particle',
        engine: 'particles',
        colorA: '#ffcc66',
        colorB: '#ff6600',
        alphaStart: 1,
        alphaEnd: 0,
        sizeStart: 20,
        sizeEnd: 3,
        glow: 14,
        spawnRate: 18,
        speedMin: 1.5,
        speedMax: 6,
        angle: -90,
        spread: 70,
        gravity: 0.035,
        lifetime: 82,
        emitterX: 640,
        emitterY: 460
      }
    },
    {
      id: 'electric-discharge',
      label: 'Electric Arc',
      engine: 'electric-arc',
      description: 'Jagged blue-white chained lightning with branches and flicker.',
      config: {
        name: 'Electric Arc',
        engine: 'electric-arc',
        appearanceMode: 'brush',
        builtInBrush: 'slash',
        colorA: '#e9ffff',
        colorB: '#4f8dff',
        alphaStart: 1,
        alphaEnd: 0,
        sizeStart: 4,
        sizeEnd: 1,
        glow: 30,
        spawnRate: 34,
        speedMin: 1.4,
        speedMax: 4.8,
        angle: -90,
        spread: 52,
        gravity: -0.004,
        lifetime: 22,
        emitterX: 640,
        emitterY: 360,
        rotationMode: 'fixed',
        rotationJitter: 18,
        arcLength: 82,
        arcBranches: 3,
        arcJaggedness: 18,
        arcFlicker: 0.7
      }
    },
    {
      id: 'projectile-core',
      label: 'Projectile Core',
      engine: 'projectile',
      description: 'Dense forward burst for fireballs or thrown magic.',
      config: {
        name: 'Projectile Core',
        engine: 'projectile',
        colorA: '#fff1a8',
        colorB: '#ff2d00',
        alphaStart: 1,
        alphaEnd: 0,
        sizeStart: 26,
        sizeEnd: 2,
        glow: 28,
        spawnRate: 26,
        speedMin: 4,
        speedMax: 10,
        angle: 0,
        spread: 30,
        gravity: 0.01,
        lifetime: 65,
        emitterX: 420,
        emitterY: 370
      }
    },
    {
      id: 'magic-trail',
      label: 'Magic Trail / Ribbon',
      engine: 'ribbon',
      description: 'Purple trail particles for good magic or Songspell residue.',
      config: {
        name: 'Magic Trail / Ribbon',
        engine: 'ribbon',
        colorA: '#d65cff',
        colorB: '#5830ff',
        alphaStart: 0.85,
        alphaEnd: 0,
        sizeStart: 28,
        sizeEnd: 7,
        glow: 32,
        spawnRate: 22,
        speedMin: 0.5,
        speedMax: 3.8,
        angle: 0,
        spread: 120,
        gravity: 0,
        lifetime: 110,
        emitterX: 460,
        emitterY: 430
      }
    },
    {
      id: 'shockwave-pulse',
      label: 'Shockwave Pulse',
      engine: 'shockwave',
      description: 'A clean expanding pulse ring with fast fade and optional centre bloom.',
      config: {
        name: 'Shockwave Pulse',
        engine: 'shockwave',
        colorA: '#ffffff',
        colorB: '#8eeaff',
        alphaStart: 0.85,
        alphaEnd: 0,
        sizeStart: 8,
        sizeEnd: 3,
        glow: 18,
        spawnRate: 6,
        speedMin: 0,
        speedMax: 0,
        angle: 0,
        spread: 360,
        gravity: 0,
        lifetime: 48,
        emitterX: 640,
        emitterY: 360,
        shockwaveRadius: 245,
        shockwaveThickness: 9,
        shockwaveCenterFlash: 0.28
      }
    },
    {
      id: 'radial-burst',
      label: 'Radial Burst',
      engine: 'ring',
      description: 'Radial particle bloom like the older shockwave-looking burst.',
      config: {
        name: 'Radial Burst',
        engine: 'ring',
        colorA: '#ffffff',
        colorB: '#8eeaff',
        alphaStart: 0.9,
        alphaEnd: 0,
        sizeStart: 10,
        sizeEnd: 26,
        glow: 18,
        spawnRate: 64,
        speedMin: 5,
        speedMax: 8,
        angle: 0,
        spread: 360,
        gravity: 0,
        lifetime: 45,
        emitterX: 640,
        emitterY: 360
      }
    },
    {
      id: 'soft-smoke',
      label: 'Soft Smoke / Gas Base',
      engine: 'gas',
      description: 'Low contrast smoke grains with slow upward drift.',
      config: {
        name: 'Soft Smoke / Gas Base',
        engine: 'gas',
        colorA: '#d4d0c8',
        colorB: '#5d5854',
        alphaStart: 0.34,
        alphaEnd: 0,
        sizeStart: 42,
        sizeEnd: 78,
        glow: 0,
        spawnRate: 12,
        speedMin: 0.2,
        speedMax: 1.6,
        angle: -90,
        spread: 120,
        gravity: -0.016,
        lifetime: 160,
        emitterX: 640,
        emitterY: 520
      }
    },
    {
      id: 'shimmer-wisps',
      label: 'Shimmer Wisps',
      engine: 'refraction',
      description: 'Visible amber-blue shimmer wisps. This is not the underlay-warp heat distortion engine.',
      config: {
        name: 'Shimmer Wisps',
        engine: 'refraction',
        colorA: '#ffe0a0',
        colorB: '#6dd6ff',
        alphaStart: 0.22,
        alphaEnd: 0,
        sizeStart: 34,
        sizeEnd: 92,
        glow: 10,
        spawnRate: 10,
        speedMin: 0.15,
        speedMax: 1.1,
        angle: -90,
        spread: 70,
        gravity: -0.008,
        lifetime: 140,
        emitterX: 640,
        emitterY: 500
      }
    },
    {
      id: 'heat-distortion',
      label: 'Heat Distortion / Underlay Warp',
      engine: 'heatdistortion',
      description: 'Heat haze overlay designed to warp an image/video underlay or background below it.',
      config: {
        name: 'Heat Distortion / Underlay Warp',
        engine: 'heatdistortion',
        colorA: '#fff0b6',
        colorB: '#6dd6ff',
        alphaStart: 0.18,
        alphaEnd: 0,
        sizeStart: 80,
        sizeEnd: 140,
        glow: 4,
        spawnRate: 7,
        speedMin: 0.1,
        speedMax: 0.6,
        angle: -90,
        spread: 50,
        gravity: -0.006,
        lifetime: 120,
        emitterX: 640,
        emitterY: 500,
        distortionStrength: 12,
        distortionScale: 28
      }
    },
    {
      id: 'optic-glint',
      label: 'Optic Glint',
      engine: 'lensflare',
      description: 'Single optical sparkle/glint. Use True Lens Flare for a multi-part flare.',
      config: {
        name: 'Optic Glint',
        engine: 'lensflare',
        colorA: '#fff6c8',
        colorB: '#6de5ff',
        alphaStart: 0.92,
        alphaEnd: 0,
        sizeStart: 12,
        sizeEnd: 44,
        glow: 38,
        spawnRate: 8,
        speedMin: 0.05,
        speedMax: 0.8,
        angle: 0,
        spread: 360,
        gravity: 0,
        lifetime: 72,
        emitterX: 640,
        emitterY: 360
      }
    },
    {
      id: 'true-lens-flare',
      label: 'True Lens Flare',
      engine: 'true-lensflare',
      description: 'A single-layer lens flare renderer with halo, streak, ghost orbs, and hot core.',
      config: {
        name: 'True Lens Flare',
        engine: 'true-lensflare',
        colorA: '#fff8d6',
        colorB: '#7be7ff',
        alphaStart: 0.95,
        alphaEnd: 0,
        sizeStart: 36,
        sizeEnd: 48,
        glow: 42,
        spawnRate: 2,
        speedMin: 0,
        speedMax: 0.15,
        angle: 0,
        spread: 6,
        gravity: 0,
        lifetime: 90,
        emitterX: 640,
        emitterY: 360,
        flareStreakLength: 320,
        flareGhosts: 4,
        flareHalo: 72,
        rotationMode: 'fixed',
        rotationJitter: 0
      }
    },
    {
      id: 'rising-spell-text',
      label: 'Rising Spell Text',
      engine: 'particles',
      description: 'Glowing text particles that can rise, fade, and drift like a spell chant.',
      config: {
        name: 'Rising Spell Text',
        engine: 'particles',
        appearanceMode: 'shape',
        particleShape: 'text',
        textContent: 'AETHERA',
        textAlign: 'center',
        textFont: 'Cinzel, Georgia, serif',
        textWeight: '700',
        textStroke: true,
        textStrokeWidth: 2,
        textLetterSpacing: 1,
        colorA: '#fff7cf',
        colorB: '#d65cff',
        alphaStart: 0.85,
        alphaEnd: 0,
        sizeStart: 24,
        sizeEnd: 10,
        glow: 26,
        spawnRate: 4,
        speedMin: 0.4,
        speedMax: 1.2,
        angle: -90,
        spread: 18,
        gravity: -0.012,
        lifetime: 120,
        emitterX: 640,
        emitterY: 470
      }
    }
  ]
};

export const BASE_EFFECT_PRESETS = PRESETS_REGISTRY;

export function cloneBasePreset(category, id) {
  const group = PRESETS_REGISTRY[category] || [];
  const preset = group.find((item) => item.id === id);
  return preset ? JSON.parse(JSON.stringify(preset)) : null;
}

export function listBaseCategories() {
  return Object.keys(PRESETS_REGISTRY);
}

export function listBasePresets() {
  return Object.values(PRESETS_REGISTRY).flat();
}
