import { APP_SCHEMA, EDGE_STYLE_LABELS, LAYOUT_STYLE_LABELS } from './config.js';
import { state } from './state.js';

function gridName(node) {
  const letterIndex = node.y;
  let letters = '';
  let n = letterIndex;
  do {
    letters = String.fromCharCode(65 + (n % 26)) + letters;
    n = Math.floor(n / 26) - 1;
  } while (n >= 0);
  return `${letters}${node.x + 1}`;
}

function collectCellOverrides() {
  const overrides = [];
  const size = state.mazeMatrix.length;
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const color = state.colorMatrix?.[y]?.[x];
      const textureSlot = state.textureMatrix?.[y]?.[x];
      if (color || textureSlot !== null) {
        overrides.push({ x, y, grid: gridName({ x, y }), color: color || null, textureSlot });
      }
    }
  }
  return overrides;
}

export function buildGameJson() {
  const now = new Date().toISOString();
  return {
    schema: APP_SCHEMA,
    kind: 'puzzle_module',
    editor: {
      name: 'Artifex Maze Maker',
      version: '1.0.0',
      exportedAt: now
    },
    game: 'Forever Bound',
    moduleId: state.moduleId,
    displayName: state.displayName || 'Labyrinth Maze',
    gameplayMode: state.gameplayMode,
    puzzle: {
      type: state.puzzleType,
      callingText: state.callingText,
      completionCondition: {
        flag: state.completionFlag,
        value: true,
        trigger: 'player_reaches_exit_cell'
      },
      start: {
        x: state.startNode.x,
        y: state.startNode.y,
        grid: gridName(state.startNode)
      },
      exit: {
        x: state.endNode.x,
        y: state.endNode.y,
        grid: gridName(state.endNode)
      }
    },
    grid: {
      cols: state.mazeMatrix.length,
      rows: state.mazeMatrix.length,
      cellSize: 1,
      origin: 'top_left',
      wallValue: 1,
      pathValue: 0,
      matrix: state.mazeMatrix
    },
    collision: {
      type: 'grid_solid_cells',
      solidValue: 1,
      navigableValue: 0,
      playerRadiusCells: 0.34
    },
    renderHints: {
      preview3d: true,
      wallHeight: Number(state.wallHeight),
      wallGap: Number(state.gap),
      layoutStyle: LAYOUT_STYLE_LABELS[state.layoutStyle]?.toLowerCase() || 'straight',
      edgeStyle: EDGE_STYLE_LABELS[state.edgeStyle]?.toLowerCase() || 'sharp',
      wallMaterialPreset: state.wallMaterialPreset,
      defaultWallColor: state.wallColor,
      floorStyle: state.floorStyle,
      shadows: Boolean(state.shadows),
      lightAngle: Number(state.lightAngle),
      cellOverrides: collectCellOverrides()
    },
    entities: [
      {
        id: `${state.moduleId}_entry`,
        type: 'entry_point',
        role: 'maze_start',
        grid: gridName(state.startNode),
        x: state.startNode.x,
        y: state.startNode.y
      },
      {
        id: `${state.moduleId}_exit`,
        type: 'completion_trigger',
        role: 'maze_exit',
        grid: gridName(state.endNode),
        x: state.endNode.x,
        y: state.endNode.y,
        setsFlag: state.completionFlag
      }
    ],
    solution: {
      optional: true,
      algorithm: 'breadth_first_search',
      path: state.solutionPath || []
    },
    notes: 'Generated by Artifex Maze Maker. This JSON is intended for the Forever Bound data-driven puzzle/objective pipeline.'
  };
}

export function downloadGameJson() {
  const data = buildGameJson();
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${state.moduleId || 'artifex_maze'}_puzzle.json`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export async function copyGameJsonToClipboard() {
  const text = JSON.stringify(buildGameJson(), null, 2);
  await navigator.clipboard.writeText(text);
}

export function importGameJson(data) {
  if (!data || !data.grid?.matrix) throw new Error('This file does not contain an Artifex maze grid matrix.');
  state.moduleId = data.moduleId || state.moduleId;
  state.displayName = data.displayName || state.displayName;
  state.gameplayMode = data.gameplayMode || state.gameplayMode;
  state.puzzleType = data.puzzle?.type || state.puzzleType;
  state.callingText = data.puzzle?.callingText || state.callingText;
  state.completionFlag = data.puzzle?.completionCondition?.flag || state.completionFlag;
  state.mazeMatrix = data.grid.matrix;
  state.gridSize = data.grid.matrix.length;
  state.startNode = { x: data.puzzle?.start?.x ?? 1, y: data.puzzle?.start?.y ?? 1 };
  state.endNode = { x: data.puzzle?.exit?.x ?? state.gridSize - 2, y: data.puzzle?.exit?.y ?? state.gridSize - 2 };
  state.wallHeight = data.renderHints?.wallHeight ?? state.wallHeight;
  state.gap = data.renderHints?.wallGap ?? state.gap;
  state.wallMaterialPreset = data.renderHints?.wallMaterialPreset || state.wallMaterialPreset;
  state.wallColor = data.renderHints?.defaultWallColor || state.wallColor;
  state.floorStyle = data.renderHints?.floorStyle || state.floorStyle;
  state.solutionPath = data.solution?.path || [];

  const size = state.gridSize;
  state.colorMatrix = Array.from({ length: size }, () => Array(size).fill(null));
  state.textureMatrix = Array.from({ length: size }, () => Array(size).fill(null));
  data.renderHints?.cellOverrides?.forEach((item) => {
    if (item.y >= 0 && item.y < size && item.x >= 0 && item.x < size) {
      state.colorMatrix[item.y][item.x] = item.color || null;
      state.textureMatrix[item.y][item.x] = item.textureSlot ?? null;
    }
  });
}
