export const SHIMMER_PRESETS = [
  {
    id: 'portal-threshold',
    name: 'Portal Threshold',
    description: 'Layered radial shimmer for route exits, portals, limbo tears and magical thresholds.',
    tags: ['portal', 'route-exit', 'radial', 'magic'],
    values: {
      type: 'portal',
      radius: 64,
      softness: 44,
      scaleX: 96,
      scaleY: 122,
      strength: 68,
      refraction: 62,
      waveSize: 36,
      waveSpeed: 46,
      swirl: 42,
      noise: 34,
      glow: 76,
      rimWidth: 54,
      rimAlpha: 74,
      chromatic: 38,
      blur: 24,
      pulse: 52,
      coreColor: '#45d7ff',
      rimColor: '#8e4dff',
      accentColor: '#ffc15f',
      backdropColor: '#09080f',
      sourceMode: 'color',
      cloudiness: 96,
      textureStrength: 68,
      wispAmount: 92,
      wispSpeed: 42,
      wispSize: 54,
      wispCurl: 44,
      particleAmount: 76,
      particleSpeed: 62,
      particleSpread: 64,
      particleSize: 48,
      renderScale: 58,
      cellSize: 6,
      positionX: 50,
      positionY: 50,
      durationSec: 8,
      loopIntensity: 64,
      loop: true,
      showGrid: true,
      showMask: true
    }
  },
  {
    id: 'heat-shimmer',
    name: 'Heat Shimmer',
    description: 'Horizontal mirage distortion for fire, hot air, desert haze and invisible magical pressure.',
    tags: ['refraction', 'heat', 'mirage', 'air'],
    values: {
      type: 'heat',
      radius: 86,
      softness: 70,
      scaleX: 170,
      scaleY: 58,
      strength: 36,
      refraction: 78,
      waveSize: 24,
      waveSpeed: 58,
      swirl: 0,
      noise: 48,
      glow: 18,
      rimWidth: 18,
      rimAlpha: 20,
      chromatic: 12,
      blur: 42,
      pulse: 18,
      coreColor: '#ffe0a3',
      rimColor: '#ff8a3d',
      accentColor: '#fff1d4',
      backdropColor: '#110b06',
      sourceMode: 'color',
      cloudiness: 62,
      textureStrength: 68,
      wispAmount: 46,
      wispSpeed: 42,
      wispSize: 54,
      wispCurl: 44,
      particleAmount: 34,
      particleSpeed: 46,
      particleSpread: 64,
      particleSize: 28,
      renderScale: 58,
      cellSize: 6,
      positionX: 50,
      positionY: 48,
      durationSec: 6,
      loopIntensity: 72,
      loop: true,
      showGrid: true,
      showMask: false
    }
  },
  {
    id: 'dream-ripple',
    name: 'Dream Ripple',
    description: 'Soft memory/dream-state distortion for underworld visions, limbo overlays and Oracle moments.',
    tags: ['dream', 'limbo', 'ripple', 'screen-overlay'],
    values: {
      type: 'dream',
      radius: 74,
      softness: 82,
      scaleX: 118,
      scaleY: 92,
      strength: 44,
      refraction: 52,
      waveSize: 62,
      waveSpeed: 28,
      swirl: -22,
      noise: 18,
      glow: 54,
      rimWidth: 26,
      rimAlpha: 40,
      chromatic: 22,
      blur: 54,
      pulse: 62,
      coreColor: '#b6e5ff',
      rimColor: '#d783ff',
      accentColor: '#f2e2ff',
      backdropColor: '#0a0712',
      sourceMode: 'color',
      cloudiness: 62,
      textureStrength: 68,
      wispAmount: 46,
      wispSpeed: 42,
      wispSize: 54,
      wispCurl: 44,
      particleAmount: 34,
      particleSpeed: 46,
      particleSpread: 64,
      particleSize: 28,
      renderScale: 58,
      cellSize: 6,
      positionX: 50,
      positionY: 50,
      durationSec: 10,
      loopIntensity: 46,
      loop: true,
      showGrid: true,
      showMask: true
    }
  },
  {
    id: 'transition-tear',
    name: 'Transition Tear',
    description: 'Short violent displacement for scene transitions, cursed cuts and magical fractures.',
    tags: ['transition', 'tear', 'screen', 'distortion'],
    values: {
      type: 'transition',
      radius: 92,
      softness: 38,
      scaleX: 142,
      scaleY: 86,
      strength: 86,
      refraction: 72,
      waveSize: 18,
      waveSpeed: 84,
      swirl: 68,
      noise: 76,
      glow: 48,
      rimWidth: 38,
      rimAlpha: 52,
      chromatic: 70,
      blur: 68,
      pulse: 82,
      coreColor: '#dceeff',
      rimColor: '#ff514c',
      accentColor: '#33f0d8',
      backdropColor: '#080606',
      sourceMode: 'color',
      cloudiness: 62,
      textureStrength: 68,
      wispAmount: 46,
      wispSpeed: 42,
      wispSize: 54,
      wispCurl: 44,
      particleAmount: 34,
      particleSpeed: 46,
      particleSpread: 64,
      particleSize: 28,
      renderScale: 58,
      cellSize: 6,
      positionX: 50,
      positionY: 50,
      durationSec: 3,
      loopIntensity: 22,
      loop: false,
      showGrid: true,
      showMask: true
    }
  }
];

export function clonePreset(preset) {
  return JSON.parse(JSON.stringify(preset));
}
