export const SHIMMER_PRESETS = [
  {
    id: 'portal-threshold',
    name: 'Portal Ring',
    description: 'A dark central aperture outlined by circular wispy energy, broken arcs and small sparks.',
    tags: ['portal', 'ring', 'aperture', 'magic'],
    values: {
      type: 'ring',
      radius: 50,
      softness: 36,
      scaleX: 94,
      scaleY: 104,
      strength: 30,
      refraction: 26,
      waveSize: 38,
      waveSpeed: 58,
      swirl: 78,
      noise: 30,
      glow: 54,
      rimWidth: 50,
      rimAlpha: 68,
      chromatic: 18,
      blur: 12,
      pulse: 52,
      coreColor: '#32f1ff',
      rimColor: '#8e4dff',
      accentColor: '#ffca66',
      backdropColor: '#05070f',
      sourceMode: 'color',
      cloudiness: 46,
      textureStrength: 68,
      wispAmount: 64,
      wispSpeed: 58,
      wispSize: 54,
      wispCurl: 82,
      particleAmount: 34,
      particleSpeed: 68,
      particleSpread: 72,
      particleSize: 16,
      renderScale: 100,
      cellSize: 1,
      positionX: 50,
      positionY: 50,
      durationSec: 8,
      loopIntensity: 66,
      loop: true,
      showGrid: true,
      showMask: true
    }
  },
  {
    id: 'wormhole-tunnel',
    name: 'Wormhole Tunnel',
    description: 'A softer spiralling tunnel/vortex with fewer cloudy ribbons and an irregular breathing outer haze.',
    tags: ['wormhole', 'vortex', 'spiral', 'tunnel'],
    values: {
      type: 'wormhole',
      radius: 64,
      softness: 54,
      scaleX: 136,
      scaleY: 84,
      strength: 54,
      refraction: 42,
      waveSize: 58,
      waveSpeed: 58,
      swirl: 86,
      noise: 26,
      glow: 54,
      rimWidth: 46,
      rimAlpha: 46,
      chromatic: 22,
      blur: 24,
      pulse: 62,
      coreColor: '#28dfff',
      rimColor: '#255bff',
      accentColor: '#b65cff',
      backdropColor: '#020611',
      sourceMode: 'color',
      cloudiness: 58,
      textureStrength: 72,
      wispAmount: 54,
      wispSpeed: 66,
      wispSize: 58,
      wispCurl: 88,
      particleAmount: 30,
      particleSpeed: 74,
      particleSpread: 64,
      particleSize: 14,
      renderScale: 100,
      cellSize: 1,
      positionX: 50,
      positionY: 50,
      durationSec: 10,
      loopIntensity: 76,
      loop: true,
      showGrid: true,
      showMask: false
    }
  },
  {
    id: 'heat-shimmer',
    name: 'Heat Shimmer',
    description: 'Horizontal mirage distortion for fire, hot air, desert haze and invisible magical pressure.',
    tags: ['refraction', 'heat', 'mirage', 'air'],
    values: {
      type: 'heat',
      radius: 86,
      softness: 70,
      scaleX: 170,
      scaleY: 58,
      strength: 36,
      refraction: 78,
      waveSize: 24,
      waveSpeed: 58,
      swirl: 0,
      noise: 48,
      glow: 18,
      rimWidth: 18,
      rimAlpha: 20,
      chromatic: 12,
      blur: 42,
      pulse: 18,
      coreColor: '#ffe0a3',
      rimColor: '#ff8a3d',
      accentColor: '#fff1d4',
      backdropColor: '#110b06',
      sourceMode: 'color',
      cloudiness: 0,
      textureStrength: 68,
      wispAmount: 0,
      wispSpeed: 42,
      wispSize: 0,
      wispCurl: 44,
      particleAmount: 0,
      particleSpeed: 46,
      particleSpread: 64,
      particleSize: 0,
      renderScale: 100,
      cellSize: 1,
      positionX: 50,
      positionY: 48,
      durationSec: 6,
      loopIntensity: 72,
      loop: true,
      showGrid: true,
      showMask: false
    }
  },
  {
    id: 'transition-tear',
    name: 'Transition Tear',
    description: 'Short violent displacement for scene transitions, cursed cuts and magical fractures.',
    tags: ['transition', 'tear', 'screen', 'distortion'],
    values: {
      type: 'transition',
      radius: 82,
      softness: 12,
      scaleX: 10,
      scaleY: 165,
      strength: 96,
      refraction: 84,
      waveSize: 8,
      waveSpeed: 96,
      swirl: 0,
      noise: 94,
      glow: 34,
      rimWidth: 18,
      rimAlpha: 46,
      chromatic: 90,
      blur: 18,
      pulse: 88,
      coreColor: '#e6f7ff',
      rimColor: '#ff514c',
      accentColor: '#33f0d8',
      backdropColor: '#080606',
      sourceMode: 'color',
      cloudiness: 0,
      textureStrength: 68,
      wispAmount: 0,
      wispSpeed: 42,
      wispSize: 54,
      wispCurl: 44,
      particleAmount: 62,
      particleSpeed: 46,
      particleSpread: 64,
      particleSize: 16,
      renderScale: 100,
      cellSize: 1,
      positionX: 50,
      positionY: 50,
      durationSec: 3,
      loopIntensity: 22,
      loop: false,
      showGrid: true,
      showMask: false
    }
  }
];

export function clonePreset(preset) {
  return JSON.parse(JSON.stringify(preset));
}
