const TAU = Math.PI * 2;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)));
const clamp01=v=>clamp(v,0,1);
const scale=(min,max,v)=>min+(max-min)*clamp01(v);
const smoothstep=(a,b,v)=>{const t=clamp01((v-a)/Math.max(.0001,b-a));return t*t*(3-2*t)};
const fract=v=>v-Math.floor(v);
const hash1=v=>fract(Math.sin(v*127.1)*43758.5453123);
const hash2=(x,y)=>fract(Math.sin(x*127.1+y*311.7)*43758.5453123);
function hexToRgb(hex){const s=String(hex||'#fff').replace('#','').trim();const f=s.length===3?s.split('').map(c=>c+c).join(''):s.padEnd(6,'0').slice(0,6);const n=parseInt(f,16);return{r:(n>>16)&255,g:(n>>8)&255,b:n&255}}
function rgba(hex,a=1){const c=hexToRgb(hex);return `rgba(${c.r}, ${c.g}, ${c.b}, ${a})`}
function cover(iw,ih,tw,th){const ir=iw/Math.max(1,ih),tr=tw/Math.max(1,th);let w=tw,h=th;if(ir>tr){h=th;w=h*ir}else{w=tw;h=w/ir}return{x:(tw-w)/2,y:(th-h)/2,width:w,height:h}}
export class ShimmerDistortionEngine{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.gridCanvas=document.createElement('canvas');this.grid=this.gridCanvas.getContext('2d');this.textureImage=null;this.values={};this.gridKey=''}
 setValues(v){this.values={...v}}
 setTextureImage(img=null){this.textureImage=img}
 resize(){const r=Math.max(1,Math.min(1.6,window.devicePixelRatio||1)),rect=this.canvas.getBoundingClientRect(),w=Math.max(720,Math.round(rect.width*r)),h=Math.max(405,Math.round(rect.height*r));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.gridCanvas.width=w;this.gridCanvas.height=h;this.gridKey=''}}
 geo(t){const v=this.values,w=this.canvas.width,h=this.canvas.height,base=Math.min(w,h)*scale(.08,.62,(v.radius??60)/100),pulse=1+Math.sin(t*scale(.4,4,(v.pulse??45)/100))*.035*((v.loopIntensity??50)/100);return{w,h,cx:w*((v.positionX??50)/100),cy:h*((v.positionY??50)/100),base,rx:Math.max(.01,base*((v.scaleX??100)/100)*pulse),ry:Math.max(.01,base*((v.scaleY??100)/100)*pulse)}}
 draw(t=0){this.resize();const g=this.geo(t),v=this.values,ctx=this.ctx;ctx.clearRect(0,0,g.w,g.h);ctx.fillStyle=v.backdropColor||'#09080f';ctx.fillRect(0,0,g.w,g.h);if(v.showGrid)this.drawGrid(g);this.drawShimmer(ctx,g,t);if(v.type==='heat'){this.drawHeat(ctx,g,t);return}if(v.type==='dream'){this.drawDream(ctx,g,t);return}if(v.type==='transition'){this.drawTransition(ctx,g,t);return}this.drawCore(ctx,g,t);this.drawRim(ctx,g,t);this.drawWisps(ctx,g,t);this.drawParticles(ctx,g,t);this.drawGlow(ctx,g)}
 drawGrid(g){const v=this.values,key=`${g.w}x${g.h}|${v.coreColor}|${v.rimColor}|${v.accentColor}|${v.backdropColor}`;if(this.gridKey!==key){this.gridKey=key;const c=this.grid;c.clearRect(0,0,g.w,g.h);const major=Math.max(34,Math.round(g.w/16)),minor=Math.max(17,Math.round(g.w/32));c.lineWidth=Math.max(1,g.w/900);for(let x=0;x<=g.w;x+=minor){c.beginPath();c.moveTo(x,0);c.lineTo(x,g.h);c.strokeStyle=x%major===0?rgba(v.coreColor,.18):rgba(v.coreColor,.055);c.stroke()}for(let y=0;y<=g.h;y+=minor){c.beginPath();c.moveTo(0,y);c.lineTo(g.w,y);c.strokeStyle=y%major===0?rgba(v.rimColor,.14):rgba(v.rimColor,.045);c.stroke()}}this.ctx.drawImage(this.gridCanvas,0,0)}
 drawShimmer(ctx,g,t){const v=this.values,str=scale(0,.28,(v.strength??50)/100),ref=scale(0,.22,(v.refraction??50)/100),ws=scale(.005,.08,(v.waveSize??40)/100),spd=scale(.15,4.8,(v.waveSpeed??40)/100),soft=scale(.06,.55,(v.softness??50)/100),step=v.type==='heat'?Math.max(4,Math.round(g.h/90)):Math.max(5,Math.round(g.h/130));ctx.save();ctx.globalCompositeOperation='lighter';for(let y=0;y<g.h;y+=step){const ny=(y-g.cy)/Math.max(1,g.ry);for(let x=0;x<g.w;x+=step*2){const nx=(x-g.cx)/Math.max(1,g.rx),d=Math.sqrt(nx*nx+ny*ny),mask=v.type==='heat'?Math.max(0,1-Math.abs(ny)*.9):1-smoothstep(1-soft,1.08,d);if(mask<=.01)continue;const wave=v.type==='heat'?Math.sin(y*ws*2.8+t*spd*2.2):Math.sin(d/ws+t*spd+Math.atan2(ny,nx)*3);const a=Math.max(0,(str*.20+ref*.16)*mask);ctx.strokeStyle=rgba(v.coreColor,a);ctx.lineWidth=Math.max(1,step*.32);ctx.beginPath();const off=wave*str*step*4*mask;ctx.moveTo(x+off,y);ctx.lineTo(x+step*2+off,y+wave*step*.7);ctx.stroke()}}ctx.restore()}
 drawHeat(ctx,g,t){const v=this.values;ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<22;i++){const y=g.cy-g.ry*.9+(i/21)*g.ry*1.8,a=.035+.04*Math.sin(i*.7+t);ctx.strokeStyle=rgba(v.accentColor,a);ctx.lineWidth=Math.max(1,g.h/540);ctx.beginPath();for(let x=0;x<=g.w;x+=18){const yy=y+Math.sin(x*.014+t*1.6+i*.4)*g.ry*.035;if(x===0)ctx.moveTo(x,yy);else ctx.lineTo(x,yy)}ctx.stroke()}ctx.restore()}
 drawCore(ctx,g,t){const v=this.values;ctx.save();ctx.beginPath();ctx.ellipse(g.cx,g.cy,g.rx,g.ry,0,0,TAU);ctx.clip();const fill=ctx.createRadialGradient(g.cx,g.cy,g.base*.05,g.cx,g.cy,Math.max(g.rx,g.ry));fill.addColorStop(0,rgba(v.coreColor,.22));fill.addColorStop(.55,rgba(v.accentColor,.07));fill.addColorStop(1,rgba(v.rimColor,.16));ctx.fillStyle=fill;ctx.fillRect(g.cx-g.rx*1.4,g.cy-g.ry*1.4,g.rx*2.8,g.ry*2.8);if(v.sourceMode==='texture'&&this.textureImage){const r=cover(this.textureImage.width,this.textureImage.height,g.rx*2.7,g.ry*2.3);ctx.globalAlpha=scale(.15,.92,(v.textureStrength??70)/100);ctx.drawImage(this.textureImage,g.cx-g.rx*1.35+r.x,g.cy-g.ry*1.15+r.y,r.width,r.height);ctx.globalAlpha=1}else{ctx.globalAlpha=.08;ctx.strokeStyle=rgba(v.coreColor,.65);ctx.lineWidth=Math.max(1,g.base*.012);for(let i=0;i<9;i++){ctx.beginPath();for(let x=-g.rx*1.3;x<=g.rx*1.3;x+=10){const y=Math.sin(x*.03+t*(1.1+i*.08)+i)*g.ry*.16+(i-4)*g.ry*.09;if(x<=-g.rx*1.3)ctx.moveTo(g.cx+x,g.cy+y);else ctx.lineTo(g.cx+x,g.cy+y)}ctx.stroke()}ctx.globalAlpha=1}ctx.restore()}
 point(g,a,off,t,seed,noise){const n=(hash2(Math.cos(a)*9.1+seed,Math.sin(a)*10.7+t*.14)-.5)*off*noise;return{x:g.cx+Math.cos(a)*(g.rx+n),y:g.cy+Math.sin(a)*(g.ry+n*.72)}}
 drawRim(ctx,g,t){const v=this.values,cloud=(v.cloudiness??60)/100,rw=scale(6,38,(v.rimWidth??44)/100),alpha=scale(.05,.40,(v.rimAlpha??46)/100),glow=scale(8,34,(v.glow??46)/100),arcs=Math.round(scale(42,118,cloud));ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<arcs;i++){const seed=i*2.37,start=TAU*hash1(seed+1),len=scale(.018,.105,hash1(seed+4))*scale(.65,1.35,cloud),skip=hash1(seed+Math.floor(t*3)*.03);if(skip<.22)continue;const col=i%5===0?v.accentColor:i%2===0?v.coreColor:v.rimColor;ctx.strokeStyle=rgba(col,alpha*scale(.35,.9,hash1(seed+6)));ctx.lineWidth=Math.max(1,rw*scale(.025,.095,hash1(seed+7)));ctx.shadowColor=col;ctx.shadowBlur=glow;ctx.beginPath();for(let s=0;s<=6;s++){const a=start+len*(s/6),p=this.point(g,a,rw*2.15,t,seed+s,scale(.6,1.6,cloud));if(s===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.stroke()}const specks=Math.round(scale(18,54,cloud));for(let i=0;i<specks;i++){const seed=i*4.91,a=TAU*hash1(seed+t*.03),p=this.point(g,a,rw*2.4,t,seed,scale(.8,1.8,cloud)),r=scale(.5,2.2,hash1(seed+2))*scale(.7,1.25,cloud),col=i%3===0?v.accentColor:i%2===0?v.coreColor:v.rimColor;ctx.fillStyle=rgba(col,alpha*.55);ctx.shadowColor=col;ctx.shadowBlur=glow*.6;ctx.beginPath();ctx.arc(p.x,p.y,r,0,TAU);ctx.fill()}ctx.restore()}
 drawWisps(ctx,g,t){const v=this.values,n=Math.round(scale(0,36,(v.wispAmount??44)/100));if(!n)return;const sp=scale(.16,1.7,(v.wispSpeed??42)/100),lenBase=scale(18,78,(v.wispSize??34)/100),curl=scale(.1,1.7,(v.wispCurl??44)/100);ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<n;i++){const seed=i*7.17,p=fract(t*sp*.12+hash1(seed)),a=TAU*hash1(seed+8)+Math.sin(t*.55+seed)*curl,d=scale(g.base*.08,g.base*1.5,p),x=g.cx+Math.cos(a)*d*(g.rx/g.base),y=g.cy+Math.sin(a)*d*(g.ry/g.base),al=(.08+hash1(seed+1)*.16)*Math.sin((1-p)*Math.PI),col=i%2?v.coreColor:v.accentColor;ctx.strokeStyle=rgba(col,al);ctx.lineWidth=scale(.8,2.2,hash1(seed+3));ctx.shadowColor=col;ctx.shadowBlur=scale(4,18,hash1(seed+4));ctx.beginPath();for(let s=0;s<=5;s++){const q=s/5,aa=a+Math.sin(q*TAU+t+seed)*.28*curl,dd=d-q*lenBase;const px=g.cx+Math.cos(aa)*dd*(g.rx/g.base),py=g.cy+Math.sin(aa)*dd*(g.ry/g.base);if(s===0)ctx.moveTo(x,y);else ctx.lineTo(px,py)}ctx.stroke()}ctx.restore()}
 drawParticles(ctx,g,t){const v=this.values,n=Math.round(scale(0,58,(v.particleAmount??35)/100));if(!n)return;const sp=scale(.18,2.5,(v.particleSpeed??50)/100),spr=scale(.12,2,(v.particleSpread??70)/100),sz=scale(1.2,5.8,(v.particleSize??25)/100);ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<n;i++){const seed=i*17.17,p=fract(t*sp*.2+hash1(seed+2.9)),a=TAU*hash1(seed+1.1)+Math.sin(t*.7+seed)*spr,d=scale(g.base*.06,g.base*1.72,p),x=g.cx+Math.cos(a)*d*(g.rx/g.base),y=g.cy+Math.sin(a)*d*(g.ry/g.base),s=sz*(1-p*.58)*(0.7+hash1(seed+3.6)*.65),al=(.18+hash1(seed+4.2)*.32)*Math.sin((1-p)*Math.PI),col=i%3===0?v.accentColor:i%2===0?v.coreColor:v.rimColor;ctx.fillStyle=rgba(col,al);ctx.shadowColor=col;ctx.shadowBlur=s*5;ctx.beginPath();ctx.arc(x,y,s,0,TAU);ctx.fill()}ctx.restore()}
 drawDream(ctx,g,t){const v=this.values;this.drawCore(ctx,g,t);ctx.save();ctx.globalCompositeOperation='lighter';ctx.filter='blur(1.2px)';for(let i=0;i<9;i++){const phase=t*.35+i*.7,rx=g.rx*scale(.32,1.18,i/8),ry=g.ry*scale(.28,1.05,i/8),al=scale(.035,.11,1-i/9);ctx.strokeStyle=rgba(i%2?v.rimColor:v.coreColor,al);ctx.lineWidth=Math.max(1,g.base*.006);ctx.beginPath();for(let s=0;s<=120;s++){const a=TAU*(s/120),wave=Math.sin(a*3+phase)*g.base*.025+Math.sin(a*5-phase)*g.base*.012,x=g.cx+Math.cos(a)*(rx+wave),y=g.cy+Math.sin(a)*(ry+wave*.72);if(s===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}for(let i=0;i<18;i++){const seed=i*8.3,p=fract(t*.08+hash1(seed)),a=TAU*hash1(seed+4),d=scale(g.base*.08,g.base*1.05,p),x=g.cx+Math.cos(a)*d*(g.rx/g.base),y=g.cy+Math.sin(a)*d*(g.ry/g.base),r=scale(1,4,hash1(seed+2));ctx.fillStyle=rgba(v.accentColor,.08*Math.sin((1-p)*Math.PI));ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill()}ctx.restore();this.drawGlow(ctx,g)}
 drawTransition(ctx,g,t){const v=this.values;ctx.save();ctx.globalCompositeOperation='lighter';const tearX=g.cx+Math.sin(t*2.3)*g.base*.04;const height=g.ry*1.4,width=Math.max(2,g.rx*.34);const grad=ctx.createLinearGradient(tearX-width,g.cy,tearX+width,g.cy);grad.addColorStop(0,rgba(v.rimColor,0));grad.addColorStop(.48,rgba(v.coreColor,.20));grad.addColorStop(.52,rgba(v.accentColor,.18));grad.addColorStop(1,rgba(v.rimColor,0));ctx.fillStyle=grad;ctx.beginPath();for(let i=0;i<=28;i++){const q=i/28,y=g.cy-height+q*height*2,x=tearX+Math.sin(q*18+t*5)*width*.55+(hash1(i*2.1+Math.floor(t*10))-.5)*width*.4;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}for(let i=28;i>=0;i--){const q=i/28,y=g.cy-height+q*height*2,x=tearX+width+Math.sin(q*15-t*4)*width*.45+(hash1(i*3.7+2)-.5)*width*.5;ctx.lineTo(x,y)}ctx.closePath();ctx.fill();for(let i=0;i<18;i++){const seed=i*3.4,y=g.cy-height+hash1(seed)*height*2,x=tearX+(hash1(seed+1)-.5)*width*2.8,len=scale(g.base*.05,g.base*.24,hash1(seed+2)),col=i%2?v.rimColor:v.accentColor;ctx.strokeStyle=rgba(col,scale(.08,.32,hash1(seed+3)));ctx.lineWidth=scale(1,3,hash1(seed+4));ctx.shadowColor=col;ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(hash1(seed+5)-.5)*len,y+(hash1(seed+6)-.5)*len);ctx.stroke()}ctx.restore();this.drawParticles(ctx,g,t);this.drawGlow(ctx,g)}
 drawGlow(ctx,g){const v=this.values,glow=scale(0,.45,(v.glow??50)/100);if(!glow)return;ctx.save();ctx.globalCompositeOperation='lighter';const grad=ctx.createRadialGradient(g.cx,g.cy,g.base*.25,g.cx,g.cy,Math.max(g.rx,g.ry)*1.9);grad.addColorStop(0,rgba(v.coreColor,glow*.06));grad.addColorStop(.48,rgba(v.rimColor,glow*.08));grad.addColorStop(1,rgba(v.rimColor,0));ctx.fillStyle=grad;ctx.beginPath();ctx.ellipse(g.cx,g.cy,g.rx*1.85,g.ry*1.52,0,0,TAU);ctx.fill();ctx.restore()}
}
